[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.9.2"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true
